'use client';

import { cn } from '@/lib/utils';
import { AlertTriangle, Info } from 'lucide-react';

interface DisclaimerProps {
  variant?: 'info' | 'warning';
  title?: string;
  children: React.ReactNode;
  className?: string;
}

const variantConfig = {
  info: {
    icon: Info,
    containerClass: 'bg-primary/5 border-primary/20 text-foreground',
    iconClass: 'text-primary',
  },
  warning: {
    icon: AlertTriangle,
    containerClass: 'bg-amber-50 border-amber-200 text-amber-900 dark:bg-amber-950/30 dark:border-amber-800 dark:text-amber-200',
    iconClass: 'text-amber-600 dark:text-amber-400',
  },
};

export function Disclaimer({ variant = 'info', title, children, className }: DisclaimerProps) {
  const config = variantConfig[variant];
  const Icon = config.icon;

  return (
    <div
      className={cn(
        'flex gap-3 rounded-lg border p-4',
        config.containerClass,
        className
      )}
      role="alert"
    >
      <Icon className={cn('h-5 w-5 flex-shrink-0 mt-0.5', config.iconClass)} />
      <div className="space-y-1">
        {title && <p className="font-medium">{title}</p>}
        <div className="text-sm opacity-90">{children}</div>
      </div>
    </div>
  );
}

export function AIDisclaimer({ className }: { className?: string }) {
  return (
    <Disclaimer variant="warning" title="AI-Generated Content" className={className}>
      <p>
        This treatment plan was generated by AI and is intended as a starting point only.
        All clinical decisions must be reviewed and approved by a licensed mental health professional.
        AI suggestions do not replace professional clinical judgment.
      </p>
    </Disclaimer>
  );
}

